-- This file was auto generated.

return {
	["nine_eleven/"] = true,
	["ultimate/"] = true,
	["AC/"] = true,
	["naisho/"] = true,
	["fruit/"] = true,
	["BXS/"] = true,
	["CUNIKWARE_config/"] = true,
	["rmenu/"] = true,
	["denzware/"] = true,
	["alloyavera/"] = true,
	["deaglerh/"] = true,
	["dreambot_config/"] = true,
	["configs/"] = true,
	["sg/images/"] = true,
	["FartClient/"] = true,
	["gbot/"] = true,
	["serj/"] = true,
	["Ilysha/"] = true,
	["IlyaWare/"] = true,
	["kennedyhack/"] = true,
	["namejeff/"] = true,
	["lokiv2.dat"] = true,
	["timeshack/"] = true,
	["NillarhHack/"] = true,
	["OubHack/"] = true,
	["penisdeda/"] = true,
	["rh/"] = true,
	["swbase_cfg/"] = true,
	["scorch/"] = true,
	["sh/"] = true,
	["majestic/"] = true,
	["coffee/"] = true
}