-- This file was auto generated.

return {
	["NillarhHack/configs/autoexec.txt"] = true,
	["NillarhHack/img/furry2.jpg"] = true,
	["NillarhHack/img/furry1.png"] = true,
	["nostalgia_normal.txt"] = true,
	["nostalgia_hvh.txt"] = true,
	["lua/menu/mainmenu.lua"] = true,
	["o_conf.dat"] = true,
	["lua/miscellaneous-gmod-stuff-main/Cheaterino/AntiScreengrab.lua"] = true,
	["lua/miscellaneous-gmod-stuff-main/Cheaterino/BitflagESP.lua"] = true,
	["pa$teware.txt"] = true,
	["pasteware_normal.txt"] = true,
	["pasteware_hvh.txt"] = true,
	["penisdeda/default.json"] = true,
	["materials/ironman.jpg"] = true,
	["materials/ironman.png"] = true,
	["Lokidev_settings.dat"] = true,
	["LokiDev_serveur_list.txt"] = true,
	["Processdev_exploit.dat"] = true,
	["lua/includes/modules/CUniformRandomStream.lua"] = true,
	["data/pwned_settings.dat"] = true,
	["newshack.txt"] = true,
	["[Reich]IP_logs.txt"] = true,
	["retard_theme.txt"] = true,
	["menuhook/lolmems.txt"] = true,
	["autizam.txt"] = true,
	["storm/settings.txt"] = true,
	["tacobot_cfg.txt"] = true,
	["TBAuth.txt"] = true,
	["thack.lua"] = true,
	["p_settings.txt"] = true,
	["p_entities.txt"] = true,
	["p_whitelist.txt"] = true,
	["p_aimkey.txt"] = true,
	["p_trigkey.txt"] = true,
	["zbot/buddylist.txt"] = true
}